remote_theme: pmarsceill/just-the-docs
title: Leren leren
description: Hoe kan je leren studeren?
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bbroeckx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
